[package]
name = "kovi"
version = "0.11.11"
edition = "2021"
description = "A OneBot V11 bot plugin framework"
license = "MPL-2.0"
authors = ["ThriceCola <thricecola@hotmail.com>"]
repository = "https://github.com/thricecola/Kovi"
readme = "README_Cargo.md"
documentation = "https://thricecola.github.io/kovi-doc/"
keywords = ["kovi", "onebot", "framework"]

[lib]
name = "kovi"
path = "src/lib.rs"

[dependencies]
regex = "1"
chrono = "0.4"
dialoguer = { version = "0.11", features = ["fuzzy-select"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
log = "0.4"
anstyle = "1"
kovi-macros = "0.4"
env_logger = { version = "0.11", default-features = false, features = [
    "auto-color",
    "color",
], optional = true }
tokio = { version = "1", features = ["full", "windows-sys"] }
tokio-tungstenite = "0.24"
futures-util = "0.3"
http = "1"
toml = "0.8"
toml_edit = "0.22"
croner = "2"
rand = "0.8"
ahash = "0.8"
parking_lot = "0.12"


[features]
default = ["logger", "save_bot_status", "plugin-access-control"]
logger = ["env_logger"]
save_bot_status = ["save_bot_admin", "save_plugin_status"]
save_bot_admin = []
save_plugin_status = []
plugin-access-control = []

message_sent = []
cqstring = []


native-tls = ["tokio-tungstenite/native-tls-vendored"]
# 兼容, 到0.12删除
rustls-tls = ["tokio-tungstenite/rustls-tls-webpki-roots"]

rustls-tls-webpki-roots = ["tokio-tungstenite/rustls-tls-webpki-roots"]

rustls-tls-native-roots = ["tokio-tungstenite/rustls-tls-native-roots"]
